version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-container
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  ms-client:
    container_name: client-container
    build:
      context: ./
      dockerfile: ./ms-client/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./data/h2:/opt/h2
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest

    depends_on:
      - rabbitmq

  ms-account:
    container_name: account-container
    build:
      context: ./
      dockerfile: ./ms-account/Dockerfile
    ports:
      - "9090:9090"
    volumes:
      - ./data/h2:/opt/h2
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest

    depends_on:
      - rabbitmq

volumes:
  rabbitmq_data: